### ISSUE TITLE
As a customer, I want the application to reliably send automated emails after the customer has completed a purchase.

### ISSUE THREAD

**Issue by zikky17** [KYH-Net23/EmailProvider#12]
# Acceptance Criterias 

- [x]  The order confirmation email should be received by the customers registered email.
- [x]  The order confirmation email should contain all the necessary information about the customer’s purchase, such as products, payment, shipping, price etc.   
- [x]  After the purchase the customer should be redirected to a confirmation page with a relevant message on the screen.
- [x]  Only the correctly authorized services should be able to send an email. They should be authorized using the Token Provider.

# TASKS

- [x] #22

- [x] #23

- [x] #24

- [x] #25

- [x] #26 
- [x] #27

- [x] #28

![activity-email-provider](https://github.com/user-attachments/assets/9f533c25-a5b2-4cdd-9ab7-ca3ebf2d2785)

![sequence-email-provider](https://github.com/user-attachments/assets/0396b0d7-e925-4f98-9b14-4f96a2891c51)

# Test Case Descriptions

Test case 1:
- [ ] The email can only be sent if the OrderConfirmationModel requirements are valid.
Prerequisites:
A Customer / Guest has completed a purchase.
Steps:
The Customer / Guest finishes the checkout process.
Expected result:
We receive a code 200 back from EmailProvider

Test case 2:
- [ ] The email cannot only be sent if the OrderConfirmationModel requirements is invalid.
Prerequisites:
A Customer / Guest has completed a purchase.
Steps:
The Customer / Guest finishes the checkout process.
Expected result:
We receive a code 4xx back from EmailProvider
