### ISSUE TITLE
 As a customer, I want the application to reliably send a verification email when the user has created a new account by registering.

### ISSUE THREAD

**Issue by zikky17** [KYH-Net23/EmailProvider#4]
Acceptance Criterias 

- [x] The verification email must be sent to the newly registered user email
- [x] The user can not log in before verifying their email.
- [x] Trying to login without a confirmed email will redirect to another page, prompting the user to verify themselves.
- [x] The system must send emails securely.

TASKS

- [x] KYH-Net23/EmailProvider#14

- [x] KYH-Net23/EmailProvider#13

- [x] KYH-Net23/EmailProvider#15

- [x] KYH-Net23/EmailProvider#16

- [x] KYH-Net23/Rika#260

- [x] KYH-Net23/EmailProvider#18

- [x] KYH-Net23/EmailProvider#20

- [x] KYH-Net23/EmailProvider#21

Test Case Descriptions

Test case 1:
- [ ] The verification process can not be called unless the passcode form is filled in correctly.
Prerequisites:
A guest has gone to the verification page.
Steps:
The guest tries to submit an empty form
Expected result:
An error message is displayed on the frontend and no method is called.

![TPB1xjem3CRlUGgB4xn2UnX8e5t6jAsCUzQOOj4cLUoMyVPB7JhHxS-fKVspl-zpicMnKOQkDNemnK_62DNmgoDX-84DiKGh57nfYhDjoLb1K6YFOgdbqj05rgyaAFTf0t953-i7yiP0KTanDVeH8rq8NPwng-imU2bJ_JDwZDFmin9r7jLRvZeud8Zl0mx_b0zTiZ3LAlJkJKc58jP8](https://github.com/user-attachments/assets/713b800e-aea8-48e7-92e6-fd63f49a2cd8)

![bLEn4j904EtlAtQejCWCXLKA1cJKeKDnh6pMkmLsIFRYtHxAtviZ97fCA4otRz_BllScMKV5eAbj35hr0ROfgcyfc0w3ikKEHM6nSoJAUeDzy5Ts51Q04KQqv7wZm4UsgEobvF-xAJMRf6SIdLMLkrAtnnYjTmG72bUsT1UCO4dzq28tvPlla35ZPAXMKwGQlj29e_RenbgVHCsuwcb5](https://github.com/user-attachments/assets/4251cd7c-d318-46c4-b6ba-889a9e2c97f7)

Test case 2:
- [ ]  Entering a non-existing passcode should return
Prerequisites:
The customer has received a valid passcode.
Steps:
The customer enters an incorrect passcode.
Expected result:
We receive a 4xx back from the verification provider.

**Comment by KimmoKAhola** [comment]
task 1 done. Complete it when the user story is complete with tasks
